### ISSUE TITLE
Context menu rendering issues (black box around context menus)

### ISSUE THREAD

**Issue by dr-baba** [Guerra24/Firefox-UWP-Style#51] opened 2022-04-17 08:47 UTC
There is a black box around all context menus when I right click anywhere (on the menu bar, bookmarks bar or the content).

![image](https://user-images.githubusercontent.com/50979846/163707098-b25bd118-0a98-4fc5-aed4-0df3b4e448c2.png)
![image](https://user-images.githubusercontent.com/50979846/163707100-f348cb99-5026-456a-bad4-e9ba498754b2.png)

However this is not present when opening (left clicking) the application menu/overflow menu on the top right.

I'm using Firefox beta v100 on Windows 11 beta build 22598.100. I am using the sunvalley theme with mica.

I have tried toggling `gfx.webrender.dcomp-win.enabled` and `layout.css.backdrop-filter.enabled` to no avail.

Also acrylic does not seem to be working anywhere with/out `layout.css.backdrop-filter.enabled` but mica is working fine.

I might also add there is a white bar at the bottom of the history popup (which goes away after resizing the window). 
![image](https://user-images.githubusercontent.com/50979846/163707712-5c83c473-7b63-43ab-8bea-83ca42af98da.png)

This theme is perfect except that issue, any fixes? Thanks

**Comment by Guerra24** [comment] 2022-04-17 09:07
That's new, I'm running stable Win11 and the only issue I have seen is the white bar but that can be fixed by disabling `gfx.webrender.dcomp-win.enabled` and restarting Firefox.

What happens if you go into `css/context.css` and add `border-radius: 0px !important;` in the menupopup selector? Restart Firefox afterwards.
![image](https://user-images.githubusercontent.com/9023392/163707880-633c5b35-220c-4073-97b0-ae440504da83.png)

Acrylic is disabled because backdrop-filter is not working, I'm waiting for [1749625](https://bugzilla.mozilla.org/show_bug.cgi?id=1749625) which should land in nightly next week.

I don't have an insider vm on hand but if the issue continues I could setup one.

**Comment by dr-baba** [comment] 2022-04-17 09:41
That didn't work unfortunately.

But I tried installing this theme on firefox in a Windows 11(dev) VM and it seems to not have this issue. I'm not sure, maybe it's something corrupt, might have to reinstall firefox?

**Comment by Guerra24** [comment] 2022-04-17 09:49
I see... I'm gonna setup a vm and test it there.

I would suggest creating a new firefox profile and trying it there too, just in case it might be a configuration issue. Aside from that idk until I can reproduce it.

**Comment by Guerra24** [comment] 2022-04-17 10:27
Works fine here. It could be a configuration issue in the profile.

![image](https://user-images.githubusercontent.com/9023392/163710535-155e53cb-6bde-4ec6-9f63-c291fb0be499.png)
![image](https://user-images.githubusercontent.com/9023392/163710538-56186829-c11f-420d-b3e2-a3308a248122.png)

**Comment by dr-baba** [comment] 2022-04-18 01:10
I have created a new profile and reinstalled the theme and it seems to have fixed it, thanks for your help.

Another thing I noticed is the bottom of text cutting of in the search bar. 
![image](https://user-images.githubusercontent.com/50979846/163739561-6ae2e801-016e-42e4-a04b-05cc794be2f0.png)

**Comment by dr-baba** [comment] 2022-05-03 23:35
@Guerra24 any fixes for the text cutting off? Or is it just on my end?

**Comment by Guerra24** [comment] 2022-05-04 00:56
It's on my end too. Don't worry, I just haven't had any time to work on this.
![image](https://user-images.githubusercontent.com/9023392/166609936-b03e8dcd-82de-4325-9a97-ddc6ef312d55.png)

**Closed as completed** 2022-05-08 05:20 UTC
