### ISSUE TITLE
Mica is broken when switching light/dark theme

### ISSUE THREAD

**Issue by maicol07** [Guerra24/Firefox-UWP-Style#52] opened 2022-04-21 08:16 UTC
Mica keeps being light, while I've switched to dark theme. Restarting firefox applies the new theme, but when switching back to light Mica keeps being dark.

Example recording:
https://user-images.githubusercontent.com/9463142/164411021-6c01c808-e77a-4f65-b40b-f8c8bcdf615a.mp4

**Comment by Guerra24** [comment] 2022-04-22 00:16
Mica material is applied externally, Firefox does not call any of the apis that activate it or decide what theme to use. If you want to change it while it is open do it through MicaForEveryone.

![image](https://user-images.githubusercontent.com/9023392/164570491-aae28d81-e1b4-40f1-a48e-9512e98483df.png)

**Comment by maicol07** [comment] 2022-04-22 07:45
Oh, yes you're right, I've missed that options (was set to Default). Switching that together with the Firefox theme works great!

Thank you.

Closing...

**Comment by maicol07** [comment] 2022-04-25 21:29
@Guerra24 I have to reopen this since there is an unfixed issue. When the theme changes and firefox is closed, the next reopening is still the previous Mica theme.
See this issue for more details: MicaForEveryone/MicaForEveryone#64

**Comment by Guerra24** [comment] 2022-04-26 03:06
> When the theme changes and firefox is closed, the next reopening is still the previous Mica theme.

https://user-images.githubusercontent.com/9023392/165211664-b699644d-e2b5-4592-8160-5c720a17ce6c.mp4

Works here. MFE's Firefox rule is set to *System*.

**Comment by maicol07** [comment] 2022-04-28 07:41
🤔 I already have the same rule but the issue persists...

**Comment by dongle-the-gadget** [comment] 2022-04-29 17:03
@Guerra24 I can also reproduce the issue, however not in the order that you shown in the video, maybe do in this order instead:
1. Open Firefox. Confirm that the correct theme (dark/light) is rendered.
2. Close Firefox.
3. Change the theme
4. Reopen Firefox. Confirm that it renders the wrong theme.

In your video, you changed the theme before closing Firefox, which doesn't seem to trigger this bug.

EDIT: Reproducing video

https://user-images.githubusercontent.com/29563098/165994125-f82fb5a8-00d9-41c5-96d3-419fc79a39cf.mp4

**Comment by Guerra24** [comment] 2022-04-30 01:27
Well, that's acrylic... afaik it does not have theme-specific colors. Also since I'm running stable Win11 I have not tested any of the other backdrop types. Regardless, I tried and still works just fine.

https://user-images.githubusercontent.com/9023392/166085146-fdc4e9c0-7cd7-4e13-a9bd-7299301dd2a5.mp4

That aside this is something I can't fix from my side unfortunately.

**Comment by dongle-the-gadget** [comment] 2022-04-30 01:34
The same happens with Mica actually (sorry for the horrible video btw). And also looks like we are running dev builds while you are running stable. I generally think this is a bug related to Firefox, since this behavior doesn't shown on any other apps, only Firefox.

https://user-images.githubusercontent.com/29563098/166085443-477d66c0-1a14-4dad-96ae-da8186843c9f.mp4

.

**Comment by Guerra24** [comment] 2022-05-22 01:34
Closing this since the issue is unfixable from my side.

**Closed as completed by Guerra24** 2022-05-22 01:34 UTC

**Comment by maicol07** [comment] 2022-06-04 13:40
I've found a workaround for this issue: I've written an AutoHotKey script that automatically triggers reload when theme has changed and Firefox window is active (or is opened):  
https://github.com/maicol07/AHK-scripts/blob/main/FixFirefoxMFE.ahk

Feel free to improve the script if you want!

**Comment by Guerra24** [comment] 2022-06-19 06:22
Just upgraded to 22621 and so far no issues on my side in both stable and nightly.

**Comment by dongle-the-gadget** [comment] 2022-06-19 06:52
Strange, it still happens on my machine (25140). It looks like Firefox is automatically changing `DWMWA_USE_IMMSERIVE_DARK_MODE`, because when I delay execution of `DwmSetWindowAttribute`, everything works perfectly.

**Comment by dongle-the-gadget** [comment] 2022-06-19 06:59
After some Google digging, this problem is most likely caused by Firefox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1734359
https://hg.mozilla.org/integration/autoland/rev/b94153cca1f7

**EDIT:** The title bar bug happens even without MFE, or any other program messing with Firefox's immersive dark mode attributes. So, it's definitely a Firefox bug.

**EDIT 2:** Firefox uses a function within the `LookAndFeel` class in order to determine whether it should use dark mode for the title bars. In the `LookAndFeel.h` file, the function returns the value of a field. Haven't managed to find out where the field is set though, nor the source file of the `LookAndFeel` class (commonly it would be `LookAndFeel.cpp`, but the file is missing).

**EDIT 3:** Looks like this function is to blame: https://github.com/mozilla/gecko-dev/blob/master/widget/LookAndFeel.h#L391.

**Comment by Guerra24** [comment] 2022-06-19 07:32
Btw are you all sure Titlebar color is set to System in MFE? I can replicate the issue when set to Default but with System it does work just fine.

https://user-images.githubusercontent.com/9023392/174470587-967a970b-c4eb-4915-aed2-3badf6a49144.mp4

**Comment by dongle-the-gadget** [comment] 2022-06-19 07:33
> Btw are you all sure Titlebar color is set to System in MFE? I can replicate the issue when set to Default but with System it does work just fine.

Yes. And as I said before, it does not matter whether MFE is used or not. This is a bug within Firefox, not MFE or this theme.

**Comment by dongle-the-gadget** [comment] 2022-06-19 07:35
Whether MFE works or not in this case is pretty much a hit or miss. Some systems have Firefox applying dark theme before MFE and doesn't cause this bug; while others have MFE applying dark theme first, leading to this bug.

**Comment by dongle-the-gadget** [comment] 2022-06-19 07:38
On my system, Firefox takes like 3 seconds to initialize, while MFE only needs like 1 for applying the title bar color to Firefox. Yours looks pretty much instant.

**Comment by Guerra24** [comment] 2022-06-19 07:45
Okay, so this is the issue. Firefox theme detection is somehow *off by one* and since it's a bug *in* Firefox it can be reported through bugzilla and it should be valid since the issue is visible when the titlebar is enabled. I can do it but I'm not sure when, if you want to do it just let me know otherwise some time next week I will.

**Comment by dongle-the-gadget** [comment] 2022-06-19 07:51
You can go ahead.
