### ISSUE TITLE
Recent changes break autoscroll cursor

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#58] opened 2022-05-11 23:19 UTC
Middle-clicking the mouse to engage autoscroll should make the autoscroll mouse cursor appear - this one: 

![image](https://user-images.githubusercontent.com/58130821/167962767-9a6af0fb-88b6-4282-a5b3-4dc35b3b3ede.png)

Since the recent changes, this is just a transparent square.

**Comment by Guerra24** [comment] 2022-05-12 00:07
Duplicate of #56

**Closed as completed by Guerra24** 2022-05-12 00:07 UTC
Labels: duplicate
