### ISSUE TITLE
Sun Valley breaks style of autoscroll indicator (when middle click on page) 

### ISSUE THREAD

**Issue by emvaized** [Guerra24/Firefox-UWP-Style#79] opened 2023-06-13 23:22 UTC
Here's how it looks: 
![illustration](https://github.com/Guerra24/Firefox-UWP-Style/assets/37851576/565ad9fd-c874-40cb-9ca7-3dba64bd80e0) 

How it's supposed to look: 
![illustration](https://github.com/Guerra24/Firefox-UWP-Style/assets/37851576/1f0fafc8-e494-4fba-9525-39f984a0716d)

I belive these lines from `base.css` are to blame — when you comment them out, autoscroll style is fixed, but all navbar popups become broken (such as "Add to bookmarks" popup, Downloads popup, etc):

```
@media (-moz-windows-compositor) {
	.panel-arrowbox + slot[part="content"] {
		margin: 0px !important;
		box-shadow: none !important;
		background-clip: padding-box !important;
		border: 1px solid var(--uwp-context-border) !important;
	}

	slot[part="content"]:only-child {
		margin: var(--uwp-popup-padding) !important;
		border: 1px solid var(--uwp-context-border) !important;
		border-radius: var(--uwp-tags-overlay-radius) !important;
		background: var(--uwp-context-background) !important;
		background-clip: padding-box !important;
		box-shadow: var(--uwp-shadow-context) !important;
		overflow: clip !important;
	}
}
```

**Comment by emvaized** [comment] 2023-06-14 04:34
It turns out, replacing `background:` with `background-color:` solves the issue with non-visible icon: 
![illustration](https://github.com/Guerra24/Firefox-UWP-Style/assets/37851576/840b957f-185e-4034-a016-4f8d3a71411a) 

But still, the stylying is broken due to clipped content and squary shape

**Comment by Guerra24** [comment] 2023-06-17 01:24
Hi, this is a known issue that is unfixable right now, sorry.

Duplicate of #56

**Closed as not planned by Guerra24** 2023-06-17 01:24 UTC
Labels: duplicate
